server:
  port: 8090

spring:
  application:
    name: cliente

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
      
holamundo:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule