server:
  port: 9080

endpoints:
  bus:
    sensitive: false
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victorherrerocazurro/RepositorioConfiguraciones
  rabbitmq:
    host: localhost
    port: 5672